"""remove columns in document table

Revision ID: 0c3196951a62
Revises: 6571ed734305
Create Date: 2025-09-10 12:31:38.650488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c3196951a62'
down_revision: Union[str, Sequence[str], None] = '6571ed734305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partnership_levels_id'), table_name='partnership_levels')
    op.drop_table('partnership_levels')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partnership_levels',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('partnership_name', postgresql.ENUM('DROP_SHIPPING', 'CONSIGNMENT', 'IMPORT_EXPORT', 'WHOLESALE', 'EXHIBITION', 'AUCTION', 'WHITE_LABEL', 'BRICK_MORTRAR', 'DESIGN_COLLABORATION', 'STORYTELLING', 'TRAINER', 'CRAFT_RD', 'INVESTOR', 'NGO_POLICY', 'SUBSIDIARY', 'KPI_LEADER', 'WAREHOUSE', 'PACKAGING', 'LOGISTICS', 'MUSEUM_INSTITUTIONAL', 'NGO_GOVERNMENT', 'TECHNOLOGY_PARTNERSHIP', name='partnershiplevel'), autoincrement=False, nullable=False),
    sa.Column('prices', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('partnership_levels_pkey')),
    sa.UniqueConstraint('partnership_name', name=op.f('partnership_levels_partnership_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_partnership_levels_id'), 'partnership_levels', ['id'], unique=False)
    # ### end Alembic commands ###
