"""update teams table

Revision ID: 1c5e8538cf47
Revises: 674ec541b16b
Create Date: 2025-08-23 17:40:55.272444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c5e8538cf47'
down_revision: Union[str, Sequence[str], None] = '674ec541b16b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_members', sa.Column('image_path', sa.String(), nullable=True))
    op.drop_column('team_members', 'image')
    op.drop_column('team_members', 'bio')
    op.alter_column('teams', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_constraint(op.f('teams_parent_id_fkey'), 'teams', type_='foreignkey')
    op.drop_column('teams', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('teams_parent_id_fkey'), 'teams', 'teams', ['parent_id'], ['id'])
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=False)
    op.alter_column('teams', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('team_members', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('team_members', sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('team_members', 'image_path')
    # ### end Alembic commands ###
