"""UPDATE TABLES

Revision ID: 2285639eafb8
Revises: 2a7b753565cc
Create Date: 2025-08-17 17:16:14.688088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2285639eafb8'
down_revision: Union[str, Sequence[str], None] = '2a7b753565cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kpi_score', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('partnership_level', sa.String(), nullable=True))
    op.add_column('users', sa.Column('retention_period', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'retention_period')
    op.drop_column('users', 'partnership_level')
    op.drop_column('users', 'kpi_score')
    # ### end Alembic commands ###
