"""update notification columns

Revision ID: 27d7952487e3
Revises: d220b6f85087
Create Date: 2025-08-28 15:39:32.334027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27d7952487e3'
down_revision: Union[str, Sequence[str], None] = 'd220b6f85087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'user_id')
    # ### end Alembic commands ###
