"""UPDATE TABLES

Revision ID: 2a7b753565cc
Revises: a82e495df503
Create Date: 2025-08-16 14:39:16.571146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a7b753565cc'
down_revision: Union[str, Sequence[str], None] = 'a82e495df503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('appointments_user_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'user_id')
    op.add_column(
        "users",
        sa.Column("is_registered", sa.Enum("PENDING", "APPROVED", "REJECTED", name="registrationstatus"), nullable=False, server_default="PENDING")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('appointments_user_id_fkey'), 'appointments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
