"""add registration_step

Revision ID: 80ba3b3cab7f
Revises: 89f4212b4ecb
Create Date: 2025-08-20 17:33:28.521136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80ba3b3cab7f'
down_revision: Union[str, Sequence[str], None] = '89f4212b4ecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Step 1: Add column as nullable with default
    op.add_column('users', sa.Column('registration_step', sa.Integer(), nullable=True, server_default="0"))

    # Step 2: Backfill (optional, if needed)
    op.execute("UPDATE users SET registration_step = 0 WHERE registration_step IS NULL")

    # Step 3: Drop default if you don’t want it persisted
    op.alter_column('users', 'registration_step', server_default=None, nullable=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registration_step')
    # ### end Alembic commands ###
