"""add registration_step

Revision ID: 89f4212b4ecb
Revises: 9393d9ec87a6
Create Date: 2025-08-20 17:11:33.740005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89f4212b4ecb'
down_revision: Union[str, Sequence[str], None] = '9393d9ec87a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registration_step', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registration_step')
    # ### end Alembic commands ###
