"""add column in user table

Revision ID: 99d187b7f3e6
Revises: 7120a59eb7b0
Create Date: 2025-09-10 16:01:44.625998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99d187b7f3e6'
down_revision: Union[str, Sequence[str], None] = '7120a59eb7b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_register', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'first_register')
    # ### end Alembic commands ###
