"""next change

Revision ID: c2baec940431
Revises: b8c1a7524d57
Create Date: 2025-08-10 16:42:57.204736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2baec940431'
down_revision: Union[str, Sequence[str], None] = 'b8c1a7524d57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_members_id'), 'team_members', ['id'], unique=False)
    op.add_column('registration_info', sa.Column('business_legal_structure', sa.String(length=100), nullable=False))
    op.add_column('registration_info', sa.Column('year_established', sa.Integer(), nullable=True))
    op.add_column('registration_info', sa.Column('business_registration_number', sa.String(length=100), nullable=False))
    op.add_column('registration_info', sa.Column('brand_affiliations', sa.String(length=500), nullable=True))
    op.add_column('registration_info', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('registration_info', sa.Column('annual_turnover', sa.String(length=100), nullable=True))
    op.add_column('registration_info', sa.Column('gst_number', sa.String(length=100), nullable=False))
    op.add_column('registration_info', sa.Column('tax_identification_number', sa.String(length=100), nullable=False))
    op.add_column('registration_info', sa.Column('import_export_code', sa.String(length=100), nullable=True))
    op.add_column('registration_info', sa.Column('street_address_1', sa.String(length=255), nullable=False))
    op.add_column('registration_info', sa.Column('street_address_2', sa.String(length=255), nullable=True))
    op.add_column('registration_info', sa.Column('city', sa.String(length=100), nullable=False))
    op.add_column('registration_info', sa.Column('state_region', sa.String(length=100), nullable=False))
    op.add_column('registration_info', sa.Column('postal_code', sa.String(length=20), nullable=False))
    op.add_column('registration_info', sa.Column('contact_person_name', sa.String(length=255), nullable=False))
    op.add_column('registration_info', sa.Column('contact_email', sa.String(length=255), nullable=False))
    op.add_column('registration_info', sa.Column('contact_phone', sa.String(length=50), nullable=False))
    op.add_column('registration_info', sa.Column('contact_whatsapp', sa.String(length=50), nullable=True))
    op.add_column('registration_info', sa.Column('contact_district', sa.String(length=100), nullable=False))
    op.add_column('registration_info', sa.Column('contact_pin_code', sa.String(length=20), nullable=False))
    op.add_column('registration_info', sa.Column('contact_state', sa.String(length=100), nullable=False))
    op.add_column('registration_info', sa.Column('contact_country', sa.String(length=100), nullable=False))
    op.add_column('registration_info', sa.Column('material_standard', sa.Integer(), nullable=True))
    op.add_column('registration_info', sa.Column('quality_level', sa.Integer(), nullable=True))
    op.add_column('registration_info', sa.Column('sustainability_level', sa.Integer(), nullable=True))
    op.add_column('registration_info', sa.Column('service_level', sa.Integer(), nullable=True))
    op.add_column('registration_info', sa.Column('standards_level', sa.Integer(), nullable=True))
    op.add_column('registration_info', sa.Column('ethics_level', sa.Integer(), nullable=True))
    op.add_column('registration_info', sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('registration_info', sa.Column('bank_name', sa.String(length=255), nullable=False))
    op.add_column('registration_info', sa.Column('account_name', sa.String(length=255), nullable=False))
    op.add_column('registration_info', sa.Column('account_type', sa.String(length=100), nullable=False))
    op.add_column('registration_info', sa.Column('account_number', sa.String(length=100), nullable=False))
    op.add_column('registration_info', sa.Column('ifsc_code', sa.String(length=50), nullable=False))
    op.add_column('registration_info', sa.Column('swift_bis_code', sa.String(length=50), nullable=True))
    op.add_column('registration_info', sa.Column('iban_code', sa.String(length=50), nullable=True))
    op.add_column('registration_info', sa.Column('kyc_challenges', sa.Boolean(), nullable=True))
    op.add_column('registration_info', sa.Column('gst_compliance_issues', sa.Boolean(), nullable=True))
    op.add_column('registration_info', sa.Column('fema_payment_issues', sa.Boolean(), nullable=True))
    op.add_column('registration_info', sa.Column('digital_banking_issues', sa.Boolean(), nullable=True))
    op.add_column('registration_info', sa.Column('fraud_cybersecurity_issues', sa.Boolean(), nullable=True))
    op.add_column('registration_info', sa.Column('payment_gateway_compliance_issues', sa.Boolean(), nullable=True))
    op.add_column('registration_info', sa.Column('account_activity_issues', sa.Boolean(), nullable=True))
    op.add_column('registration_info', sa.Column('regulatory_actions', sa.Boolean(), nullable=True))
    op.alter_column('registration_info', 'business_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('registration_info', 'business_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('registration_info', 'country',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('registration_info', 'address')
    op.drop_column('registration_info', 'phone')
    op.drop_column('registration_info', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration_info', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('registration_info', sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('registration_info', sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.alter_column('registration_info', 'country',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('registration_info', 'business_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('registration_info', 'business_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('registration_info', 'regulatory_actions')
    op.drop_column('registration_info', 'account_activity_issues')
    op.drop_column('registration_info', 'payment_gateway_compliance_issues')
    op.drop_column('registration_info', 'fraud_cybersecurity_issues')
    op.drop_column('registration_info', 'digital_banking_issues')
    op.drop_column('registration_info', 'fema_payment_issues')
    op.drop_column('registration_info', 'gst_compliance_issues')
    op.drop_column('registration_info', 'kyc_challenges')
    op.drop_column('registration_info', 'iban_code')
    op.drop_column('registration_info', 'swift_bis_code')
    op.drop_column('registration_info', 'ifsc_code')
    op.drop_column('registration_info', 'account_number')
    op.drop_column('registration_info', 'account_type')
    op.drop_column('registration_info', 'account_name')
    op.drop_column('registration_info', 'bank_name')
    op.drop_column('registration_info', 'certifications')
    op.drop_column('registration_info', 'ethics_level')
    op.drop_column('registration_info', 'standards_level')
    op.drop_column('registration_info', 'service_level')
    op.drop_column('registration_info', 'sustainability_level')
    op.drop_column('registration_info', 'quality_level')
    op.drop_column('registration_info', 'material_standard')
    op.drop_column('registration_info', 'contact_country')
    op.drop_column('registration_info', 'contact_state')
    op.drop_column('registration_info', 'contact_pin_code')
    op.drop_column('registration_info', 'contact_district')
    op.drop_column('registration_info', 'contact_whatsapp')
    op.drop_column('registration_info', 'contact_phone')
    op.drop_column('registration_info', 'contact_email')
    op.drop_column('registration_info', 'contact_person_name')
    op.drop_column('registration_info', 'postal_code')
    op.drop_column('registration_info', 'state_region')
    op.drop_column('registration_info', 'city')
    op.drop_column('registration_info', 'street_address_2')
    op.drop_column('registration_info', 'street_address_1')
    op.drop_column('registration_info', 'import_export_code')
    op.drop_column('registration_info', 'tax_identification_number')
    op.drop_column('registration_info', 'gst_number')
    op.drop_column('registration_info', 'annual_turnover')
    op.drop_column('registration_info', 'website')
    op.drop_column('registration_info', 'brand_affiliations')
    op.drop_column('registration_info', 'business_registration_number')
    op.drop_column('registration_info', 'year_established')
    op.drop_column('registration_info', 'business_legal_structure')
    op.drop_index(op.f('ix_team_members_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
