"""UPDATE TABLES

Revision ID: d3ca9af1146f
Revises: ff539c32b2c3
Create Date: 2025-08-15 21:20:13.527480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3ca9af1146f'
down_revision: Union[str, Sequence[str], None] = 'ff539c32b2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('first_name', sa.String(length=255), nullable=False))
    op.add_column('appointments', sa.Column('last_name', sa.String(length=255), nullable=False))
    op.add_column('appointments', sa.Column('business_name', sa.String(length=255), nullable=False))
    op.add_column('appointments', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('appointments', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('appointments', sa.Column('phone_number', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'phone_number')
    op.drop_column('appointments', 'email')
    op.drop_column('appointments', 'website')
    op.drop_column('appointments', 'business_name')
    op.drop_column('appointments', 'last_name')
    op.drop_column('appointments', 'first_name')
    # ### end Alembic commands ###
