"""next change

Revision ID: d8b9bb8db613
Revises: e16b0b7f49e2
Create Date: 2025-08-14 00:18:53.837774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8b9bb8db613'
down_revision: Union[str, Sequence[str], None] = 'e16b0b7f49e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'document_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
