"""update appointment table

Revision ID: f07dbabbba1e
Revises: 8f0b8e54b8a5
Create Date: 2025-08-27 21:41:42.611769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f07dbabbba1e'
down_revision: Union[str, Sequence[str], None] = '8f0b8e54b8a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('appointments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'appointments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'user_id')
    # ### end Alembic commands ###
