"""UPDATE TABLES

Revision ID: ff539c32b2c3
Revises: c6ea4ac380b1
Create Date: 2025-08-15 20:36:13.731199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff539c32b2c3'
down_revision: Union[str, Sequence[str], None] = 'c6ea4ac380b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('registration_products_category_id_fkey'), 'registration_products', type_='foreignkey')
    op.drop_column('registration_products', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration_products', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('registration_products_category_id_fkey'), 'registration_products', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
